homepage:
    pattern:  /
    defaults: { _controller: PadelLeagueBundle:Default:index }

register:
  pattern: /register/
  defaults: { _controller: PadelLeagueBundle:Default:register }

classification:
  pattern: /classification/
  defaults: { _controller: PadelLeagueBundle:Default:classification }

outcome:
  pattern: /outcome/
  defaults: { _controller: PadelLeagueBundle:Default:outcome }

teams:
  pattern: /teams/
  defaults: { _controller: PadelLeagueBundle:Teams:index }

team_manager:
  pattern: /team_manager/{id}/
  defaults: { _controller: PadelLeagueBundle:Teams:manager }

team_division:
  pattern: /team_division/
  defaults: { _controller: PadelLeagueBundle:Teams:assign }

leagues:
  pattern: /leagues/
  defaults: { _controller: PadelLeagueBundle:Leagues:index }

league_manager:
  pattern: /league_manager/{id}/
  defaults: { _controller: PadelLeagueBundle:Leagues:manager }
  
create_league:
  pattern: /create_league/
  defaults: { _controller: PadelLeagueBundle:Leagues:create }
  
delete_league:
  pattern: /delete_league/{id}/
  defaults: {_controller: PadelLeagueBundle:Leagues:delete }
  
create_stage:
  pattern: /create_stage/{id}/
  defaults: { _controller: PadelLeagueBundle:Stages:create }

stage_manager:
  pattern: /stage_manager/{id}/
  defaults: { _controller: PadelLeagueBundle:Stages:manager }

delete_stage:
  pattern: /delete_stage/{id}/
  defaults: { _controller: PadelLeagueBundle:Stages:delete }
  
create_division:
  pattern: /create_division/{id}/
  defaults: { _controller: PadelLeagueBundle:Divisions:create }

division_manager:
  pattern: /division_manager/{id}/
  defaults: { _controller: PadelLeagueBundle:Divisions:manager }

delete_division:
  pattern: /delete_division/{id}/
  defaults: { _controller: PadelLeagueBundle:Divisions:delete }

login:
  pattern: /login/
  defaults: { _controller: PadelLeagueBundle:Default:login }

logout:
  pattern: /logout

login_check:
  pattern: /login_check
