homepage:
    pattern:  /
    defaults: { _controller: PadelLeagueBundle:Default:index }


register:
  pattern: /register/
  defaults: { _controller: PadelLeagueBundle:Default:register }

classification:
  pattern: /classification/
  defaults: { _controller: PadelLeagueBundle:Default:classification }

outcome:
  pattern: /outcome/
  defaults: { _controller: PadelLeagueBundle:Default:outcome }

teams:
  pattern: /teams/
  defaults: { _controller: PadelLeagueBundle:Default:teams }

leagues:
  pattern: /leagues/
  defaults: { _controller: PadelLeagueBundle:Leagues:index }

league_manager:
  pattern: /league_manager/{id}/
  defaults: { _controller: PadelLeagueBundle:Leagues:manager }
  
create_league:
  pattern: /create_league/
  defaults: { _controller: PadelLeagueBundle:Leagues:create }

login:
  pattern: /login/
  defaults: { _controller: PadelLeagueBundle:Default:login }

logout:
  pattern: /logout

login_check:
  pattern: /login_check
